name: Release JUnit Reducer

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    permissions:
          contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Env
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21.5"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}