name: Test JUnit Reducer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Env
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21.5"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Go test
        run: go test ./...
      - name: GoReleaser Check
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: check