name: build & test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21.5"

      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Test
        run: |
          go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: GoReleaser Check
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3